/**
 * Gamma API Service
 * Handles communication with Gamma Generate API (v1.0)
 * 
 * Gamma is a one-shot render service that accepts a human-readable structured narrative
 * and returns a shareable deck URL.
 */

const GAMMA_API_URL = 'https://public-api.gamma.app/v1.0/generations';

export interface GammaGenerateResponse {
  id?: string;      // gammaId generated by Gamma
  url?: string;     // shareable deck URL
  error?: string;
}

/**
 * Generates a deck using Gamma API
 * 
 * @param inputText - Human-readable structured narrative (not JSON, not markdown)
 * @returns Promise with id (gammaId) and url (shareable deck URL)
 */
export async function generateDeckWithGamma(
  inputText: string
): Promise<{ id: string; url: string }> {
  const apiKey = process.env.GAMMA_API_KEY;

  if (!apiKey) {
    throw new Error('GAMMA_API_KEY environment variable is not set');
  }

  const requestBody = {
    inputText: inputText,
    textMode: 'generate', // Required: 'generate' | 'condense' | 'preserve'
  };

  console.log('🎨 Gamma API Request:', {
    url: GAMMA_API_URL,
    method: 'POST',
    inputTextLength: inputText.length,
    hasApiKey: !!apiKey,
    requestBodyPreview: inputText.substring(0, 200) + '...',
  });

  try {
    const response = await fetch(GAMMA_API_URL, {
      method: 'POST',
      headers: {
        'X-API-KEY': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    console.log('🎨 Gamma API Response Status:', response.status, response.statusText);

    if (!response.ok) {
      const errorText = await response.text();
      let errorMessage = `Gamma API error: ${response.status} ${response.statusText}`;
      
      try {
        const errorJson = JSON.parse(errorText);
        // Extract all possible error fields
        errorMessage = errorJson.error || 
                      errorJson.message || 
                      errorJson.detail ||
                      errorJson.description ||
                      errorMessage;
        
        // Log full error response for debugging
        console.error('❌ Gamma API error response:', {
          status: response.status,
          statusText: response.statusText,
          errorJson,
          errorText,
        });
      } catch {
        // If parsing fails, use the raw text
        if (errorText) {
          errorMessage += ` - ${errorText}`;
        }
        console.error('❌ Gamma API error (non-JSON):', {
          status: response.status,
          statusText: response.statusText,
          errorText,
        });
      }

      // Handle rate limits
      if (response.status === 429) {
        throw new Error('Gamma API rate limit exceeded. Please try again later.');
      }

      throw new Error(errorMessage);
    }

    const data: GammaGenerateResponse = await response.json();

    // Log the full response for debugging
    console.log('🎨 Gamma API response data:', JSON.stringify(data, null, 2));

    // Extract id and url from response
    if (!data.id || !data.url) {
      throw new Error(
        `Gamma API response missing required fields. Expected 'id' and 'url', got: ${JSON.stringify(data)}`
      );
    }

    return { id: data.id, url: data.url };
  } catch (error) {
    // Log the full error for debugging
    console.error('❌ Gamma API catch block error:', {
      error,
      errorType: typeof error,
      errorConstructor: error?.constructor?.name,
      errorMessage: error instanceof Error ? error.message : String(error),
      errorStack: error instanceof Error ? error.stack : undefined,
      errorString: JSON.stringify(error, Object.getOwnPropertyNames(error)),
    });

    if (error instanceof Error) {
      throw error;
    }
    
    // Handle non-Error objects (like API response errors)
    if (error && typeof error === 'object') {
      const errorDetails = JSON.stringify(error, null, 2);
      throw new Error(`Failed to generate deck with Gamma: ${errorDetails}`);
    }
    
    throw new Error(`Failed to generate deck with Gamma: ${String(error)}`);
  }
}

